---
# Install xfs package
- name: install xfs Debian
  apt: name=xfsprogs state=present

# Format external volumes in xfs
- name: Format volumes in xfs
  filesystem: fstype=xfs dev={{ disk_volume_device_1 }}

# Mount external volumes
- name: mounting new xfs filesystem
  mount: name={{ gluster_volume_node_mount_dir }} src={{ disk_volume_device_1 }} fstype=xfs state=mounted

- name: Add PPA for GlusterFS.
  apt_repository:
    repo: 'ppa:gluster/glusterfs-{{ glusterfs_ppa_version }}'
    state: present
    update_cache: yes
  register: glusterfs_ppa_added
  when: glusterfs_ppa_use

- name: Ensure GlusterFS will reinstall if the PPA was just added.
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - glusterfs-server
    - glusterfs-client
  when: glusterfs_ppa_added.changed

- name: Ensure GlusterFS is installed.
  apt:
    name: "{{ item }}"
    state: installed
    default_release: "{{ glusterfs_default_release }}"
  with_items:
    - glusterfs-server
    - glusterfs-client

- name: Ensure GlusterFS is started and enabled at boot.
  service: name=glusterfs-server state=started enabled=yes
